### ISSUE TITLE
Sample data files

### ISSUE THREAD

**Issue by roozbehsadeghian** [ottokart/punctuator2#3]
Hi,

I was trying to run the code but I was stucked in reading the data files (train, dev). Is it possible for you to provide some sample data?

**Comment by ottokart** [comment]
Hi,

There's an example in the README.md of how the sentences should look like in your dataset:
_Example: to be ,COMMA or not to be ,COMMA that is the question .PERIOD_
You might run into problems if the test dataset has too few words in it.
If your minibatch size is 128 and sequence length 200 (the default values) then training, development and test datasets should have at least 25600 words each.

**Comment by ottokart** [comment]
See ./example directory for an example dataset
