### ISSUE TITLE
How to add words to exclude them from punctuation?

### ISSUE THREAD

**Issue by sangeet2020** [ottokart/punctuator2#55]
While I have succeeded in implementing your segmenter. How do I exclude some words from segmentation and punctuation? Fo example: If I say librispeech, I want it to be punctuated as LibriSpeech and nothing else-- is there any way where I can add this hardcoded list of such words?

**Comment by sangeet2020** [comment]
While I have succeeded in implementing your segmenter. How do I exclude some words from segmentation and punctuation? Fo example: If I say librispeech, I want it to be punctuated as LibriSpeech and nothing else-- is there any way where I can add this hardcoded list of such words?

**Comment by sangeet2020** [comment]
I was wondering if you had a chance to read my query above.
@ottokart Any clues on this?
Thank You

**Comment by ottokart** [comment]
Hi!

librispeech -> LibriSpeech is a capitalization/truecasing problem and punctuator does not do that.
To use a hardcoded list you can easily post-process the results with a custom script (e.g., split the output into words and check if they exist in a predefined dictionary and replace if that's the case).

**Comment by sangeet2020** [comment]
Thanks a lot for your answer. I am closing this issue.
